### ISSUE TITLE
Include modcloth.rsyslog-file for log shipping?

### ISSUE THREAD

**Issue by jszwedko** [modcloth/ansible-role-modcloth-app#10]
Should this role include modcloth.rsyslog-file for setting up log shipping?

**Comment by jszwedko** [comment]
https://github.com/modcloth-labs/ansible-role-rsyslog-file

**Comment by rafecolton** [comment]
Wouldn't that be more of a system concern than an app concern? I guess assuming we're logging to a known location via upstart or cron

**Comment by jszwedko** [comment]
The issue with making it a system concern is that then we need to know the applications that will be on the system ahead of time to determine the log files to ship. Rsyslog doesn't support globs, so you need to specify the filenames exactly.

**Comment by jszwedko** [comment]
We could consider shipping everything in /var/log and /var/log/upstart, but the issue remains of knowing the filenames ahead of time.

**Comment by rafecolton** [comment]
Maybe a separate log rotation and shipping role?

**Comment by meatballhat** [comment]
I'm +0 on a separate role, as this is how @jszwedko is currently doing it in his playbooks and it feels like an overly verbose user experience to me.  I agree that log aggregation is more of a system concern than an application concern, but we have this issue of rsyslog not supporting globs... so I'm inclined to be OK with this role internally using the rsyslog-file role to set up some rules.  It would make me feel even better if this role didn't expose the fact that it's using a particular role to achieve this.

**Comment by jszwedko** [comment]
Per meeting we decided to add the rsyslog file role as a meta dependency of this one.

**Comment by rafecolton** [comment]
:thumbsup:

**Comment by jszwedko** [comment]
Fixed by #17
