### ISSUE TITLE
Allow piping STDIN?

### ISSUE THREAD

**Issue by jszwedko** [modcloth/ansible-role-modcloth-app#11]
Some of our applications pipe input into the docker process. Is this something we'd like to support in this role?

**Comment by rafecolton** [comment]
Do you have an example use case?  And maybe a better question is do you have an example of a case that wouldn't work without stdin?  I don't know how clean it is to attach stdin if we're using upstart

**Comment by jszwedko** [comment]
One internal to ModCloth, but basically an application that expects to receive a list of IDs to process on STDIN.

**Comment by jszwedko** [comment]
This is a crontask, I agree that it doesn't make sense for a service.

**Comment by rafecolton** [comment]
What about accepting the same list as a command-line argument?  Seems like you'd only want stdin if you don't know when your stream will end

**Comment by jszwedko** [comment]
We wanted to avoid having to bind mount anything, but that is a possibility.

**Comment by jszwedko** [comment]
Addressed by #15
