### ISSUE TITLE
Use sudo where needed

### ISSUE THREAD

**Issue by jszwedko** [modcloth/ansible-role-modcloth-app#18]
Rather than depending on the person running the role to specify sudo

**Comment by rafecolton** [comment]
Examples? Isn't this need specific to which playbook the role is used in / which hosts it is applied to?

**Comment by jszwedko** [comment]
Maybe, but it forces the includer to specify the whole playbook as sudo because it doesn't appear to be possible to specify sudo just for a role inclusion. Maybe that is OK though...

**Comment by rafecolton** [comment]
That seems fine - the user can specify sudo for just that play and have the rest of the tasks/roles in a separate play that doesn't include sudo.  Plus doesn't the need for sudo or lack thereof depend on the provision and ssh users? (both of which are specified at the playbook level)

**Comment by jszwedko** [comment]
:+1: You've convinced me.
