### ISSUE TITLE
Assumes mounted volumes are directories

### ISSUE THREAD

**Issue by jszwedko** [modcloth/ansible-role-modcloth-app#21]
Currently the upstart template assumes that mounted host volumes are directories (calls `mkdir -p` to ensure they exist), but you can also mount files via `docker run`. Do we want to support file mounting or require users of this role to mount directories only?

**Comment by rafecolton** [comment]
That is an excellent point.  I see no reason why we shouldn't support mounting files, since `-v` supports it.  Submitting a suggested implementation shortly.

**Comment by jszwedko** [comment]
Closed by #22
