### ISSUE TITLE
HipChat should be notified at the beginning/end of a deploy rather than per box

### ISSUE THREAD

**Issue by rafecolton** [modcloth/ansible-role-modcloth-app#40]
http://docs.ansible.com/playbooks_delegation.html#run-once

/cc @skisulli

**Comment by jszwedko** [comment]
We may want to change the message to not use `ansible_fqdn` and perhaps use the `env` instead in this case.

**Comment by rafecolton** [comment]
:+1:

**Comment by sullimander** [comment]
@jszwedko I agree the env would be best, also might be worth taking advantage of the colors background, yellow when it starts green on successful finish, red on failure

**Comment by jszwedko** [comment]
@skisulli Agree :+1:
