### ISSUE TITLE
Add documentation for modcloth_app_type

### ISSUE THREAD

**Issue by rafecolton** [modcloth/ansible-role-modcloth-app#6]
What are the different types, and how might they be used?

Some example playbooks might be helpful

**Comment by meatballhat** [comment]
That's the intent in the `example.yml` playbook file.  Want moar comments?

**Comment by rafecolton** [comment]
Yes indeed!

**Comment by jszwedko** [comment]
@meatballhat bump!

**Comment by rafecolton** [comment]
Closed by https://github.com/modcloth/ansible-role-modcloth-app/pull/39
