### ISSUE TITLE
Proposal: pass additional arbitrary args to `docker run`

### ISSUE THREAD

**Issue by rafecolton** [modcloth/ansible-role-modcloth-app#8]
Problem: I find myself writing custom upstart templates often, when I'll I'm doing is passing one additional argument to `docker run`

Solution: Add section to default upstart template where user can supply arbitrary args to the `docker run` command.

Example use in playbook:

``` yaml
modcloth_app_docker_args:
- "-v /foo/bar:/foo/bar"
- "--link memcached:memcached"
- "--hostname {{ hostname | default( ansible_fqdn ) }}
```

Example change to template **(warning, untested)**:

``` bash
# vim:filetype=upstart
# {{ ansible_managed }}

description "{{ modcloth_app_name }}"

start on (filesystem or runlevel [2345]) and started docker
stop on runlevel [!2345]

respawn
respawn limit 3 30

script
  docker stop {{ modcloth_app_name }} >/dev/null 2>&1 || true
  docker rm -f {{ modcloth_app_name }} >/dev/null 2>&1 || true

  docker run --rm \
    -p {{ modcloth_app_docker_port }}:{{ modcloth_app_docker_port }} \
    --env-file /etc/default/{{ modcloth_app_name }} \
    --name {{ modcloth_app_name }} \
    {% for dockeropt in modcloth_app_docker_args %}
    {{ dockeropt }} \
    {% endfor %}
    {{ modcloth_app_docker_repo }}:{{ modcloth_app_docker_tag }} {{ modcloth_app_docker_command }}
end script
```

**Comment by alexschlessinger** [comment]
:+1:  for generic upstart confs

anything else we want as a param?
(runlevel, respawn)

do we ever want to be able to specify different internal and external ports? (-p args both modcloth_app_docker_port)

are there any other docker run bits that we'd set often enough to give their own variable rather than pushing into modcloth_app_docker_args?

**Comment by jszwedko** [comment]
I like this.

**Comment by jszwedko** [comment]
Not sure where we should draw the line between "arbitrary args" and structured args like port though. Feels like we may want to remove port and let the user specify it as an argument or add the rest of the arguments as structured.

**Comment by jszwedko** [comment]
Pretty much what @alexschlessinger said

**Comment by rafecolton** [comment]
@jszwedko Agreed that we should push ports into `modcloth_app_docker_args`, since not every container will want to expose a port.  Also, there are different formats, so perhaps I want to pass `-p 127.0.0.1::3000` which means export 3000 on the host but only expose it on the localhost interface (so it can only be accessed from the container or the host).  That would not play nicely with the current setup.

@alexschlessinger this would address your question about separate ports - yeah, I think we're going to want to do that sometimes.

As for other things we might want to configure - start conditions might want to be good.  For example, in recs, I have something like this:

``` bash
start on (filesystem or runlevel [2345]) and started docker and started memcached
```

In the template, that could be represented like this:

``` jinja
start on (filesystem or runlevel [2345]) and started docker {{ modcloth_app_upstart_start_condition }}
```

**Comment by rafecolton** [comment]
Hmm, I want to pass `-v` to `docker run`, how do I ensure the directory exists on the host?  Normally that would be done with a `mkdir -p` in the upstart conf

**Comment by alexschlessinger** [comment]
imho if we need conditional something based on one of these (like the volume case) it probably wants to have structured args

**Comment by rafecolton** [comment]
@alexschlessinger like https://github.com/modcloth/ansible-role-modcloth-app/pull/13?

**Comment by jszwedko** [comment]
Handled by #13 and #12
