### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by rafecolton** [modcloth/ansible-role-modcloth-app#9]
Can this be done automatically with travis whenever we tag?

**Comment by meatballhat** [comment]
Automatic deploys seem to be possible, but are not documented AFAICT.  Requires doing an authenticated `GET` https://galaxy.ansible.com/accounts/role/refresh/1428.  Having Travis do this in an `after_success` hook seems sane to me, as the operation will only ever result in a new release if there are new tags present.

**Comment by rafecolton** [comment]
Seems good to me

**Comment by jszwedko** [comment]
:+1:

**Comment by rafecolton** [comment]
Is it possible to automate this?  We would need to include credentials in the `GET` request or use the [ansible-galaxy api](https://galaxy.ansible.com/api/v1/)
